version: '3'
services:

  #PHP Service
  cli:
    build:
      dockerfile: ./Dockerfile
    image: cli
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - '/var/www/vendor'
    environment:
      DB_DATABASE: cli
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: db
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cli
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./cli/docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
